version: '3.5'
services:
  ms-config:
    container_name: LPDM-CloudConfig
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - '28088:8888'
    restart: always