version: '3.5'
services:
  postgres:
    image: postgres:alpine
    ports:
    - '28184:5432'
    container_name: LPDM-MsStoreDB
    environment:
      POSTGRES_DB: lpdm-store
      POSTGRES_USER: lpdm
      POSTGRES_PASSWORD: lpdm
      #volumes:
      #- './sql:/docker-entrypoint-initdb.d'
    restart: always
    network_mode: bridge